### ISSUE TITLE
Cannot GET /music/url

### ISSUE THREAD

**Issue by damonsu** [Hscpro/NeteaseCloudMusic#1]
运行 sudo ./NeteaseCloudMusic 获取到musicid之后出现错误
错误在下面这行：
urldata=$(curl -s --cookie "$(cat $chedir/NeteaseCloudCookies)" http://$APIService/music/url?id=${dataid[$inx]} | jq '.')

返回：Cannot GET /music/url

MusicID: 28481189,1349292048,1313118277,561307164,1346104327,464863017,1341964346,1313354324,520482501,1340543218,410801523,1331819951,439121233,448317566,36270426,515453363,552145020,461519911,554241732,1372796676
parse error: Invalid numeric literal at line 1, column 10
Player: Player low sound quality. ID_28481189
parse error: Invalid numeric literal at line 1, column 10
Player: Player low sound quality. ID_1349292048
parse error: Invalid numeric literal at line 1, column 10
Player: Player low sound quality. ID_1313118277

**Comment by brillcn** [comment]
挖坟了，应该是API的问题我看一下。使用的是最新的NeteaseCloudMusicApi吗？

**Comment by damonsu** [comment]
哈哈，后来找出问题了官方api变成/song/url

**Comment by brillcn** [comment]
那我就照着这个改了
